

# BUILD VARIABLES
ARCH=arm-none-eabi-
BUILD_DIR=build
SRC_DIR=src

# DEBUGGING VARIABLES
ENV_DIR=env
OPENOCD_CMD=openocd
GDB_CMD=$(ARCH)gdb
OPENOCD_DIR=/usr/local/share/openocd
OPENOCD_GDB_ADDR=localhost
OPENOCD_GDB_PORT=3333
INTERFACE=jlink